pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-credentials')
        DOCKER_IMAGE_NAME = 'shin-gyeongseon/jenkins-example'
        DOCKER_IMAGE_TAG = "${env.BUILD_NUMBER}"
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Checking out source code...'
                git url: 'https://github.com/shin-gyeongseon/jenkins-example', branch: 'main'
            }
        }

        stage('Build Spring Application') {
            steps {
                echo 'Building Spring application...'
                sh 'chmod +x ./gradlew'
                sh './gradlew clean build'
            }
        }


    }

    post {
        always {
            sh 'docker logout'
        }
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}
